// Autogenerated from Pigeon (v22.6.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class FfiTrwError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "FfiTrwError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? FfiTrwError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> FfiTrwError {
  return FfiTrwError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private class FFIPigeonPigeonCodecReader: FlutterStandardReader {
}

private class FFIPigeonPigeonCodecWriter: FlutterStandardWriter {
}

private class FFIPigeonPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return FFIPigeonPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return FFIPigeonPigeonCodecWriter(data: data)
  }
}

class FFIPigeonPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = FFIPigeonPigeonCodec(readerWriter: FFIPigeonPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol FfiTRWHostApi {
  func add(a: Double, b: Double) throws -> Double
  func startTimer() throws
  func stopTimer() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class FfiTRWHostApiSetup {
  static var codec: FlutterStandardMessageCodec { FFIPigeonPigeonCodec.shared }
  /// Sets up an instance of `FfiTRWHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: FfiTRWHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let addChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ffi_right_way.FfiTRWHostApi.add\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let aArg = args[0] as! Double
        let bArg = args[1] as! Double
        do {
          let result = try api.add(a: aArg, b: bArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      addChannel.setMessageHandler(nil)
    }
    let startTimerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ffi_right_way.FfiTRWHostApi.startTimer\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startTimerChannel.setMessageHandler { _, reply in
        do {
          try api.startTimer()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startTimerChannel.setMessageHandler(nil)
    }
    let stopTimerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ffi_right_way.FfiTRWHostApi.stopTimer\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopTimerChannel.setMessageHandler { _, reply in
        do {
          try api.stopTimer()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopTimerChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol FfiTRWFlutterApiProtocol {
  func onReceiveTimerResult(result resultArg: Int64, completion: @escaping (Result<Void, FfiTrwError>) -> Void)
}
class FfiTRWFlutterApi: FfiTRWFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: FFIPigeonPigeonCodec {
    return FFIPigeonPigeonCodec.shared
  }
  func onReceiveTimerResult(result resultArg: Int64, completion: @escaping (Result<Void, FfiTrwError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.ffi_right_way.FfiTRWFlutterApi.onReceiveTimerResult\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([resultArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FfiTrwError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
